---
name: bats

director_uuid:

releases:
- {name: bosh,            version: latest}
- {name: bosh-scaleway-cpi, version: latest}
- {name: garden-linux,    version: latest}

jobs:
- name: bosh
  instances: 1
  templates:
  - {name: nats, release: bosh}
  - {name: redis, release: bosh}
  - {name: blobstore, release: bosh}
  - {name: postgres, release: bosh}
  - {name: director, release: bosh}
  - {name: health_monitor, release: bosh}
  - {name: scaleway_cpi, release: bosh-scaleway-cpi}
  - {name: garden, release: garden-linux}
  resource_pool: default
  networks:
  - {name: default, static_ips: [10.244.8.2]}

properties:
  ntp: ["0.us.pool.ntp.org"]

  nats:
    address: 127.0.0.1
    user: nats
    password: nats-password

  blobstore:
    address: 127.0.0.1
    port: 25251
    backend_port: 25552
    agent: {user: agent, password: agent-password}
    director: {user: director, password: director-password}

  postgres: &db
    host: 127.0.0.1
    port: 5432
    user: bosh
    password: bosh-password
    database: bosh

  redis:
    address: 127.0.0.1
    password: redis-password

  director:
    name: bats
    address: 127.0.0.1
    enable_snapshots: true
    cpi_job: scaleway_cpi
    db: *db

    # Compatibility with current garden networking manifest config
    ignore_missing_gateway: true

  hm:
    director_account: {user: admin, password: admin-password}

  # cpi job template
  scaleway_cpi:
    loopback_range: [100, 130]
    scaleway:
      connect_network: tcp
      connect_address: 127.0.0.1:7777
    actions:
      stemcells_dir: "/var/vcap/data/scaleway_cpi/stemcells"
      disks_dir: "/var/vcap/store/scaleway_cpi/disks"
      host_ephemeral_bind_mounts_dir: "/var/vcap/data/scaleway_cpi/ephemeral_bind_mounts_dir"
      host_persistent_bind_mounts_dir: "/var/vcap/data/scaleway_cpi/persistent_bind_mounts_dir"
    agent:
      mbus: nats://nats:nats-password@10.244.8.2:4222
      blobstore:
        provider: dav
        options:
          endpoint: http://10.244.8.2:25251
          user: agent
          password: agent-password

  # garden job template
  garden:
    listen_network: tcp
    listen_address: 0.0.0.0:7777
    disk_quota_enabled: false
    allow_host_access: true
    # todo expecting fix for this from garden team
    mount_btrfs_loopback: false

resource_pools:
- name: default
  stemcell:
    name: bosh-scaleway-ubuntu-trusty-go_agent
    version: latest
  network: default
  cloud_properties: {}

networks:
- name: default
  type: manual
  subnets:
  - range: 10.244.8.0/30
    reserved: [10.244.8.1]
    static: [10.244.8.2]
    cloud_properties: {}
- name: compilation
  type: dynamic
  cloud_properties: {}

compilation:
  workers: 5
  network: compilation
  cloud_properties: {}

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 5000 - 90000
  update_watch_time: 5000 - 15000
